### ISSUE TITLE
`Component.type` field should support `string` (for builtin types) or reference to an `Instance Component`  for user defined types

### ISSUE THREAD

**Issue by andyk** [agentos-project/agentos#408]
In this world, providing a string as a type will match that string against the components in PCS. E.g,, using `type: LocalRepo` would be equivalent to using `spec:LocalRepo` as in the following:

```
specs:
    LocalRepo:
        type: Instance
        instance_of:
            type: Class
            name: LocalRepo
            module:
               type:
               path: ./pcs/local_repo.py
               version: v0.3.0 # most recent release of PCS
               repo:
                 type: GitHubRepo
                 url: https://github.com/agentos-project/agentos

    my_local_repo:
        type: spec:LocalRepo
        path: .

    my_file:
        type: spec:File
        relative_path: ./foo/bar.txt
        repo: spec:local_repo
```
