### ISSUE TITLE
AgentOS Component System (ACS) will be able to access a centralized registry of policies and environments

### ISSUE THREAD

**Issue by nickjalbert** [agentos-project/agentos#80]
V0 target: the list will be a yaml file stored in the AgentOS repository

Each registry entry will be structured as follows:

```
component_name:
  type: [policy | environment | algorithm]
  description: [component description]
  releases:
    - name: [version_1_name]
      hash: [version_1_hash]
      github_url: [url of version 1 repo]
      class_name: [fully qualified class name of version 1]
      requirements_path: [path to version 1 requirements file]

    - name: [version_2_name]
      hash: [version_2_hash]
      github_url: [url of version 2 repo]
      class_name: [fully qualified class name of version 2]
      requirements_path: [path to version 2 requirements file]
```

for example:

```
2048:
  type: environment
  description: "An environment that simulates the 2048 game"
  releases:
    - name: 1.0.0
      hash: aeb938f
      github_url: https://github.com/example-proj/example-repo
      class_name: main.2048
      requirements_path: requirements.txt

    - name: 1.1.0
      hash: 3939aa1
      github_url: https://github.com/example-proj/example-repo
      class_name: main.2048
      requirements_path: requirements.txt
```

[See the design doc for more details](https://github.com/agentos-project/design_docs/blob/main/registry.rst).
